import React from "react";

const TermsAndConditions = () => {
    return (
        <div className="bg-gray-100 text-gray-900 p-6 min-h-screen">
        <div className="max-w-6xl mx-auto bg-white p-8 shadow-lg rounded-lg">
            <h1 className="text-[50px] font-bold text-center mb-6">Terms and Conditions</h1>

            <div className="space-y-6">
            <Section title="User's Terms of Use">
                <p>
                This legal agreement is an electronic record in terms of the Indian Information Technology Act, 2000 and rules there
                under as applicable and the amended provisions about electronic records in various statutes as amended by the Indian
                Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any
                physical or digital signatures. This legal document is published in accordance with the provisions of Rule 3 (1) of the
                Indian Information Technology (Intermediaries guidelines) Rules, 2011 and Rule 4 of the Information Technology
                (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 of Information
                Technology Act, 2000 amended through Information Technology Amendment Act, 2008 that require publishing the Terms of use
                and practices for access and usage of any functional website. We intend to ensure your steady commitment to the usage of
                this website and the services provided by us through our website
                "mayuricaeducation.in”. For the purpose of these Terms of use (“Terms of use”), wherever the context so requires, “We”, “Our”,
                and “Us” shall mean and refer to the website. “You”, “Your”, “Yourself”, “User” shall mean and refer to natural and
                legal individuals who shall be users of this website and the services provided by us or the service providers and who
                are competent to enter into binding contracts, as per Indian laws. “Third Parties” refer to any website, platform or
                individual apart from the users and the creator of this website.
                </p>
            </Section>

            <Section title="General Terms">
                <ol className="list-decimal pl-5 space-y-1">
                <li>
                    The headings of each section in these Terms of use are only for the purpose of organizing the various provisions
                    under these Terms of use in an orderly manner and shall be used by you to interpret the provisions contained herein in a
                    manner as may apply to you. Further, it is specifically agreed by you that the headings shall have legal or contractual
                    value on your usage of the website.
                </li>
                <li>The use of this website is solely governed by these Terms of use, Privacy Policy that may be uploaded on the website
                    and any modifications or amendments made thereto by us from time to time, at our sole discretion. If you as a user
                    continue to access and use this website, you are agreeing to comply with and be bound by the following Terms of use and
                    Privacy Policy.
                </li>
                <li>You expressly agree and acknowledge that these Terms of use and Privacy Policy are co-terminus in nature and that
                    expiry/termination of either one will lead to the termination of the other.
                </li>
                <li>You unequivocally agree that these Terms of use and the Privacy Policy constitute a legally binding agreement between
                    us, and that you shall be subject to the rules, guidelines, policies, terms, and conditions applicable to your use of
                    the website, and that the same shall be deemed to be incorporated into these Terms of use and shall be treated as part
                    and parcel of the same. You acknowledge and agree that no signature or express act is required to make these Terms of
                    use and the Privacy Policy binding on you and that your act of visiting any part of the website constitutes your full
                    and final acceptance of these Terms of use and the Privacy Policy.
                </li>
                <li>We reserve the sole and exclusive right to amend or modify these Terms of use without any prior permission or
                    intimation to you, and you expressly agree that any such amendments or modifications shall come into effect immediately.
                    If you do not adhere to the changes, you must stop using the website at once. Your continued use of the website will
                    signify your acceptance of the changed terms.
                </li>
                </ol>
            </Section>

            <Section title="Registration">
                <p>
                We do not provide any registration option at the moment and we may in the future incorporate the same on our website.
                Currently, you can directly avail of services by providing your personal details as specified under the privacy policy.
                </p>
            </Section>

            <Section title="Eligibility">
                <ol className="list-decimal pl-5 space-y-1">
                <li>You represent and warrant that you are competent and eligible to enter into legally binding agreements and that you
                    have the requisite authority to bind themselves to these Terms of use or represent a minor as a legally authorised
                    parent or guardian following the law. All acts of minor shall be deemed to be considered as the acts undertaken under
                    the supervision of their legal guardian.
                </li>
                <li>You further represent that you will comply with these Terms of use and all applicable local, state, national and
                    international laws, rules and regulations.
                </li>
                <li>You shall not use the website if you are not competent to contract or are disqualified from doing so by any other
                    applicable law, rule, or regulation currently in force.
                </li>
                </ol>
            </Section>

            <Section title="Payment Gateway">
                <p>
                For making all payments for purchases on the website, you shall be required to make a payment for which you will be
                redirected to a third-party payment gateway that we may have an agreement with. The payment gateway may additionally
                seek information from you to process the payment for your payment and additionally may charge you the payment gateway
                charges that may be applicable. The payment gateway consists of Debit Card/Credit Card/Net Banking/UPI and other wallet
                options. You shall be governed under the concerned payment gateway’s Terms and Conditions and other Policies for the
                purpose of all payment-related aspects.
                </p>
            </Section>

            <Section title="Content">
                <p>
                All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, brand names, descriptions,
                sounds, music, and artwork (collectively, ‘Content’), is generated/provided or based on information provided by the
                users or third parties and we have no control and make no guarantees regarding the quality, the accuracy, integrity or
                genuineness of such content or such other information provided on the website. All the Content displayed on the website
                is subject to copyright and shall not be reused by you (or a third party) without the prior written consent from us and
                the copyright owner. You are solely responsible for the integrity, authenticity, quality, and genuineness of the content
                provided on the website and whilst feedback and comments by you can be made via the website, we bear no liability
                whatsoever for any feedback or comments made by the other users or made in respect of any of the content on the website.
                </p>
            </Section>

            <Section title="Indemnity">
                <p>
                You agree to indemnify, defend and hold harmless us, and our respective directors, officers, employees and agents
                (collectively, "Parties"), from and against any losses, liabilities, claims, damages, demands, costs and expenses
                asserted against or incurred by us that arise out of, result from, or maybe payable by, any breach or non-performance of
                any representation, warranty, covenant or agreement made or obligation to be performed according to these Terms of use.
                </p>
            </Section>

            <Section title="Limitation Of Liability">
                <ol className="list-decimal pl-5 space-y-1">
                <li>We are not responsible for any consequences arising out of the following events:</li>
                    <ul class="list-disc pl-5 space-y-1">
                        <li>If the website is inoperative/non-responsive due to any connectivity errors associated with the internet connection
                        such as but not limited to slow connectivity, no connectivity, server failure.</li>
                        <li>If you have fed incorrect information or data or for any deletion of data.</li>
                        <li>If there is an undue delay or inability to communicate through email.</li>
                        <li>If there is any deficiency or defect in the services managed by us.</li>
                        <li>If there is a failure in the functioning of any other service provided by us.</li>
                    </ul>
                <li>The website accepts no liability for any errors or omissions, on behalf of itself, or for any damage caused to you,
                    your belongings, or any third party, resulting from the use or misuse of the website or any service availed of by us
                    through the website. The service and any Content or material displayed on the service is provided without any
                    guarantees, conditions, or warranties as to its accuracy, suitability, completeness, or reliability. We will not be
                    liable to you for the unavailability or failure of the website.
                </li>
                <li>You are to comply with all laws applicable to you or your activities, and with all Policies, which are hereby
                    incorporated into this Terms of use by reference.
                </li>
                <li>The website expressly excludes any liability for any loss or damage that was not reasonably foreseeable by the
                    website and which is incurred by you in connection with the website, including loss of profits; and any loss or damage
                    incurred by you as a result of your breach of these Terms of use.
                </li>
                <li>To the fullest extent permitted by law, we shall not be liable to you or any other party for any loss or damage, regardless
                    of the form of action or basis of any claim. You acknowledge and agree that your sole and exclusive remedy for any
                    dispute with us is to terminate your use of the website.
                </li>
                </ol>
            </Section>

            <Section title="Terms">
                <li>These Terms of use shall continue to form a valid and binding contract between us and shall continue to be in full force
                    and effect until you continue to access and use the Websites.
                </li>
                <li>You may terminate your use of the website at any time.
                </li>
                <li>We may terminate these Terms of use and close your account at any time without notice and/or suspend or terminate
                    your access to the website at any time and for any reason, if any discrepancy or legal issue arises.
                </li>
                <li>Such suspension or termination shall not limit our right to take any other action against you that we consider
                    appropriate.</li>
                <li>It is also hereby declared that we may discontinue the services and Websites without any prior notice.
                </li>
            </Section>

            <Section title="Termination">
                <li>We reserve the right, in its sole discretion, to unilaterally terminate your access to the website, or any portion
                    thereof, at any time, without notice or cause.</li>
                <li>We also reserve the universal right to deny access to you, to any/all of are on its website without any prior
                    notice/explanation to protect the interests of the website and/or other users to the website.</li>
                <li>We reserve the right to limit, deny or create different access to the website and its features concerning different
                    users, or to change any of the features or introduce new features without prior notice.</li>
                <li>You shall continue to be bound by these Terms of use, and it is expressly agreed to by you that you shall not have
                    the right to terminate these Terms of use till the expiry of the same.</li>
            </Section>

            <Section title="Communication">
                <p>
                By using this website and providing your identity and contact information to us through the website, you agree and
                consent to receive calls, e-mails, or SMS from us and/or any of its representatives at any time.

                You expressly agree that notwithstanding anything contained herein above, you may be contacted by us relating to any
                services availed by you on the website or anything pursuant thereto and you agree to indemnify us from any harassment
                claims. It is expressly agreed to by us that any information shared by us shall be governed by the Privacy Policy.
                </p>
            </Section>

            <Section title="User Obligations and Formal Undertakings as to Conduct">
                <p>You agree and acknowledge that you are a restricted user of this website and you:</p>

                <ul className="list-disc pl-5 space-y-1">
                    <li>Agree to provide genuine credentials whenever required on the website. You shall not use a fictitious identity. We are
                    not liable if you have provided incorrect information.</li>
                    <li>Agree to ensure the Name, Email address, Mobile number, and any such other information that may be provided and shall
                    keep your information accurate and up to date.</li>
                    <li>Understand and acknowledge that the data submitted is manually entered into the database of the website. You also
                    acknowledge the fact that data so entered into the database is for easy and ready reference for you and to streamline
                    the services through the website.</li>
                    <li>Understand and agree that, to the fullest extent permissible by law, the website or any of its affiliates or their
                    respective officers, directors, employees, agents, licensors, representatives, operational service providers,
                    advertisers, or suppliers shall not be liable for any loss or damage, of any kind, direct or indirect, in connection
                    with or arising from the use of the website or these terms of use, including, but not limited to, compensatory,
                    consequential, incidental, indirect, special, or punitive damages.</li>
                    <li>Are bound not to cut, copy, modify, recreate, reverse engineer, distribute, disseminate, post, publish, or create
                    derivative works from, transfer, or sell any information obtained from the website. Any such use/limited use of the
                    website will only be allowed with prior express written permission.</li>
                    <li>Agree not to access (or attempt to access) the website and/or the materials or services by any means other than
                    through the interface provided by the website.</li>
                    <li>Expressly agree and acknowledge that the Content generated by the users and displayed on the website is not owned by
                    us and that we are in no way responsible for the content of the same. You may, however, report any offensive or
                    objectionable content, which we may then remove from the website at our sole discretion.</li>
                </ul>

                <p>You further undertake not to:</p>

                <ul class="list-disc pl-5 space-y-1">
                    <li>Engage in any activity that interferes with or disrupts access to the website or the services provided therein (or the
                    servers and networks which are connected to the website).</li>
                    <li>Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity.</li>
                    <li>Probe, scan, or test the vulnerability of the website or any network connected to the website, nor breach the security
                    or authentication measures on the website or any network connected to the website.</li>
                    <li>Disrupt or interfere with the security of, or otherwise cause harm to, the website, system resources, accounts,
                    passwords, servers, or networks connected to or accessible through the website or any affiliated or linked websites.</li>
                    <li>Use the website or any material or content therein for any purpose that is unlawful or prohibited by these Terms of
                    Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of this website
                    or any other third party.</li>
                    <li>Violate any code of conduct or guideline which may apply for or to any particular service offered on the website.</li>
                    <li>Violate any applicable laws, rules, or regulations currently in force within or outside India.</li>
                    <li>Violate any portion of these Terms of Use or the Privacy Policy, including but not limited to any applicable
                    additional terms of the website contained herein or elsewhere, whether made by amendment, modification, or otherwise.</li>
                    <li>Commit any act that causes us to lose (in whole or in part) the services of its Internet Establishment ("ISP") or in
                    any manner disrupts the services of any other supplier/service provider of the website.</li>
                </ul>

                <p>You hereby expressly authorize us to disclose all information relating to you in our possession to law enforcement or
                    other government officials, as we may in our sole discretion, believe necessary or appropriate in connection with the
                    investigation and/or resolution of possible crimes, especially those involving personal injury and theft/infringement of
                    intellectual property.
                    By indicating your acceptance to use any services offered on the website, you are obligated to complete such
                    transactions after making payment. You shall be prohibited from indicating your acceptance to avail services where the
                    transactions have remained incomplete.
                    You agree to use the services provided by us, our affiliates, consultants, and contracted companies, for lawful purposes
                    only.
                    You agree to provide authentic and true information. We reserve the right to confirm and validate the information and
                    other details provided by you at any point in time. If upon confirmation such details are found to be false, not to be
                    true (wholly or partly), we shall in our sole discretion reject the registration and debar you from using the website
                    without prior intimation whatsoever.
                    You agree not to post any material on the website that is defamatory, offensive, obscene, indecent, abusive, or
                    needlessly distressful or advertising any goods or services. More specifically, you agree not to host, display, upload,
                    update, publish, modify, transmit, or in any manner share any information that:
                </p>

                <ul class="list-disc pl-5 space-y-1">
                    <li>Belongs to another person and to which you have no right.</li>
                    <li>Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libelous, invasive of
                    another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering
                    or gambling, or otherwise unlawful in any manner.</li>
                    <li>Is in any way harmful to minors.</li>
                    <li>Infringes any patent, trademark, copyright, or other proprietary rights.</li>
                    <li>Violates any law for the time being in force.</li>
                    <li>Deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly
                    offensive or menacing.</li>
                    <li>Threatens the unity, integrity, defence, security, or sovereignty of India, friendly relations with foreign states, or
                    public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence
                    or is insulting any other nation.</li>
                </ul>
            </Section>

            <Section title="Suspension of User Access and Activity">
                <p>Notwithstanding other legal remedies that may be available, we may in our sole discretion, limit your access and/or
                activity by immediately removing your access credentials either temporarily or indefinitely, or suspend/terminate your
                association with the website, and/or refuse usage of the website, without being required to provide you with notice or
                cause:</p>
                <ol class="list-decimal pl-5 space-y-1">
                    <li>If you are in breach of any of these Terms of Use or the Privacy Policy.</li>
                    <li>If you have provided wrong, inaccurate, incomplete, or incorrect information.</li>
                    <li>If your actions may cause any harm, damage, or loss to other users or us, at our sole discretion.</li>
                </ol>
            </Section>

            <Section title="Intellectual Property Rights">
                <p>Unless expressly agreed to in writing, nothing contained herein shall give you a right to use any of the trade names,
                trademarks, service marks, logos, domain names, information, questions, answers, solutions, reports and other
                distinctive brand features, save according to the provisions of these Terms of use that shall be available on the
                website. All logos, trademarks, brand names, service marks, domain names, including material, designs, and graphics
                created by and developed by either the website or such other third party and other distinctive brand features of the
                website are the property of the website or the respective copyright or trademark owner. Furthermore, concerning the
                website, we shall be the exclusive owner of all the designs, graphics and the like, related to the website.
                You shall not use any of the intellectual property displayed on the website in any manner that is likely to cause
                confusion among existing or prospective users of the website, or that in any manner disparages or discredits the
                website, to be determined in the sole discretion.
                You are aware all intellectual property, including but not limited to copyrights, relating to said services resides with
                the owners, and that at no point does any such intellectual property stand transferred from the creators. You are aware
                that we merely provide the website through which you can communicate with other users and the website does not own any
                of the intellectual property relating to the independent content displayed on the website, apart from created graphics
                and specified content.
                You are further aware that any reproduction or infringement of the intellectual property of the owners by you will
                result in legal action being initiated against you by the respective owners of the intellectual property so
                reproduced/infringed upon. It is agreed to by you that the contents of this section shall survive even after the
                termination or expiry of these Terms of use and/or Privacy Policy.
                </p>
            </Section>

            <Section title="Disclaimer of Warranties and Liabilities">
                <p>You further agree and undertake that you are accessing the website at your sole risk and are that you are using the best
                and prudent judgment before availing of any features on the website or accessing/using any information displayed
                thereon. You agree that any kind of information, resources, activities, recommendations obtained/availed from the
                website, written or oral, will not create any warranty and we disclaim all liabilities resulting from these. We do not
                guarantee that the features and content contained on the website will be uninterrupted or error-free, or that the
                website or its server will be free of viruses or other harmful components, and you hereby expressly accept any
                associated risks involved with your use of the website. It is further agreed to by you that the contents of this section
                shall survive even after the termination or expiry of the Terms of use and/or Privacy Policy.
                </p>
            </Section>
            </div>
        </div>
        </div>
    );
    };

    const Section = ({ title, children }) => (
    <div>
        <h2 className="text-xl font-semibold mb-2">{title}</h2>
        {children}
    </div>
);

export default TermsAndConditions;
